# Generated by Django 3.2.2 on 2021-05-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('storeName', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
